# Netlify-cms config file
backend:
  name: test-repo     # Used for create fields
#  name: github        # Used during development
#  name: git-gateway   # Used for production

  branch: master
  repo: Junscuzzy/bo

media_folder: static/uploads
public_folder: uploads

collections:
  - name: packs
    label: Packs
    folder: content/packs
    create: true
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: excerpt, label: Extrait, widget: text }
      - { name: numero, label: Numero du pack, widget: number }
      - {
          name: bgColor,
          label: Couleur du fond,
          widget: select,
          options:
            - { label: "Vert", value: "green" }
            - { label: "Rose", value: "pink" }
            - { label: "Saumon", value: "saumon" }
        }
      - {
          name: color,
          label: Couleur du texte,
          widget: select,
          options:
            - { label: "Vert", value: "green" }
            - { label: "Rose clair", value: "pinkLight" }
            - { label: "Saumon Clair", value: "saumonLight" }
      }
      - {
          name: body,
          label: Contenu,
          widget: markdown,
          hint: "Si possible, utiliser uniquement des H3 ou '###' en markdown"
      }
