# Netlify-cms config file
backend:
  name: test-repo     # Used for create fields
#  name: github        # Used during development
#  name: git-gateway   # Used for production

  branch: master
  repo: Junscuzzy/bo

media_folder: static/uploads
public_folder: uploads

collections:
  - name: packs
    label: Packs
    folder: content/packs
    create: true
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: excerpt, label: Extrait, widget: text }
      - { name: numero, label: Numero du pack, widget: number }
      - name: bgColor
        label: Couleur du fond
        widget: select
        options:
          - { label: "Vert", value: "green" }
          - { label: "Rose", value: "pink" }
          - { label: "Saumon", value: "saumon" }
      - name: color
        label: Couleur du texte
        widget: select
        options:
          - { label: "Vert", value: "green" }
          - { label: "Rose clair", value: "pinkLight" }
          - { label: "Saumon Clair", value: "saumonLight" }
      - name: body
        label: Contenu
        widget: markdown
        hint: "Si possible, utiliser uniquement des H3 ou '###' en markdown"
  - name: members
    label: Membres
    folder: content/members
    create: true
    fields:
      - { name: title, label: Nom d'affichage, widget: string }
      - { name: firstname, label: Prénom, widget: string }
      - { name: lastname, label: Nom, widget: string }
      - { name: profession, label: Profession, widget: string }
      - { name: professionCool, label: Profession Cool, widget: string }
      - { name: mail, label: Email, widget: string }
      - { name: avatar, label: Avatar, widget: image, allow_multiple: false }
      - name: bgColor
        label: Couleur du fond
        widget: select
        options:
          - { label: "Vert", value: "green" }
          - { label: "rouge", value: "red" }
          - { label: "Saumon", value: "saumon" }
      - name: color
        label: Couleur du mail
        widget: select
        options:
          - { label: "Vert", value: "green" }
          - { label: "rouge", value: "red" }
      - label: Avantages
        name: skills
        widget: list
        fields:
          - { name: label, label: Label, widget: string }
          - { name: link, label: Lien, widget: string, required: false, hint: Optionel }
      - label: "Liens sociaux"
        name: socialLinks
        widget: list
        fields:
          - { name: label, label: Label, widget: string }
          - { name: link, label: Lien, widget: string }
      - name: body
        label: "Texte de présentation"
        widget: markdown
        hint: "N'utilisez pas les fonctions de mises en forme ici."
  - name: pages
    label: Pages
    delete: false
    files:
    - name: index
      label: Bengale Studio
      file: conntent/pages/index.md
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: excerpt, label: Extrait, widget: text, hint: 'Utilisé pour le SEO' }
        - name: titles
          label: Titres qui changent
          widget: list
          default: ["Créateurs d'expériences Digitales"]
          hint: "Spérarer les expressions par une virgule."
        - name: sections
          label: Sections
          widget: list
          fields:
            - { name: title, label: Titre de section, widget: string }
            - { name: theme, label: Thème, widget: select, options: ['rose', 'rouge', 'vert'] }
            - { name: content, label: Contenu, widget: markdown }
        - { name: ctaTitle, label: Titre CTA, widget: string }
        - { name: devisBtn, label: Label du bouton devis, widget: string }
        - { name: contactBtn, label: Label du bouton contact, widget: string }
